config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get '/dashboard', to: 'users#dashboard'
  get '/about', to: 'static_pages#about'
  get '/coming_soon', to: 'static_pages#coming_soon'
  get '/demo', to: 'users#demo_sign_in'

  resources :events, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources :event_times, only: [:show, :new, :create, :edit, :update, :destroy]
  end

  resources :tickets, only: [:create]

  root 'static_pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :manager, :foreign_key => :manager_id, :class_name => "User"
  has_many :event_times, dependent: :destroy
  validates :title, presence: true, length: { maximum: 50 }
  validates :description, presence: true, length: { minimum: 50, maximum: 450 }
  validates :location, presence: true, length: { maximum: 250 }
end

app/models/event_time.rb
class EventTime < ApplicationRecord
  validates :start_time, presence: true
  validates :end_time, presence: true
  validate :end_time_after_start_time
  validate :start_time_after_now
  belongs_to :event
  has_many :tickets, dependent: :destroy
  default_scope -> { order(start_time: :asc) }
  scope :upcoming, -> { where('start_time >= ?', Time.zone.now) }
  scope :past, -> { where('start_time <= ?', Time.zone.now) }

  # returns true if the event hasn't begun yet
  def upcoming?
    start_time >= Time.zone.now
  end

  private

  # validates end time is after start time
  def end_time_after_start_time
    if start_time.present? && end_time.present?
      if end_time <= start_time
        errors.add(:end_time, "must be after start time")
      end
    end
  end

  # validates start time is after now
  def start_time_after_now
    if start_time.present?
      if start_time <= Time.zone.now
        errors.add(:start_time, "must be in the future")
      end
    end
  end

end

app/models/ticket.rb
class Ticket < ApplicationRecord
  validates :attendee_id, presence: true
  validates :event_time_id, presence: true
  belongs_to :attendee, :foreign_key => :attendee_id, :class_name => "User"
  belongs_to :event_time
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true

  has_many :managed_events, :foreign_key => "manager_id", :class_name => "Event", dependent: :destroy
  has_many :tickets, :foreign_key => "attendee_id", :class_name => "Ticket", dependent: :destroy

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/event_times_controller.rb
class EventTimesController < ApplicationController
  before_action :authenticate_user!

  def show
    @event = Event.find(params[:event_id])
    @event_time = EventTime.find(params[:id])
    @tickets = @event_time.tickets.includes(:attendee)
    unless current_user == @event.manager
      flash[:danger] = "Something went wrong."
      redirect_to dashboard_path 
    end
  end

  def new
    @event = Event.find(params[:event_id])
    @event_time = @event.event_times.build
    unless current_user == @event.manager
      flash[:danger] = "Something went wrong."
      redirect_to dashboard_path 
    end
  end

  def create
    @event = Event.find(params[:event_id])
    @event_time = @event.event_times.build(event_time_params)
    if @event_time.save
      flash[:success] = "Your event was created!"
      redirect_to event_path(@event)
    else
      render 'new'
    end
  end

  def edit
    @event = Event.find(params[:event_id])
    @event_time = EventTime.find(params[:id])
    unless current_user == @event.manager
      flash[:danger] = "Something went wrong."
      redirect_to dashboard_path 
    end
  end

  def update
    @event = Event.find(params[:event_id])
    @event_time = EventTime.find(params[:id])
    if @event_time.update(event_time_params)
      flash[:success] = "Your event was updated!"
      redirect_to event_path(@event)
    else
      render 'edit'
    end
  end

  def destroy
    @event = Event.find(params[:event_id])
    @event_time = EventTime.find(params[:id])
    @event_time.destroy
    flash[:success] = "Your showtime was cancelled!"
    redirect_to event_path(@event)
  end

  private

    def event_time_params
      params.require(:event_time).permit(:start_time, :end_time)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:show, :new, :create, :edit, :update, :destroy]

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
    @ticket = Ticket.new
  end

  def new
    @event = current_user.managed_events.build
  end

  def create
    @event = current_user.managed_events.build(event_params)
    if @event.save
      flash[:success] = "Your event was created!"
      redirect_to dashboard_path
    else
      render 'new'
    end
  end

  def edit
    @event = Event.find(params[:id])
    unless current_user == @event.manager
      flash[:danger] = "Something went wrong."
      redirect_to dashboard_path 
    end
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      flash[:success] = "Your event was updated!"
      redirect_to dashboard_path
    else
      render 'edit'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    flash[:success] = "Your event was cancelled!"
    redirect_to dashboard_url
  end

  private

    def event_params
      params.require(:event).permit(:title, :description, :location)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def about
  end

  def coming_soon
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

  def create
  	event_time = EventTime.find(params[:ticket][:event_time_id])
  	attendee = current_user
  	ticket = Ticket.new(event_time: event_time, attendee: attendee)
  	if ticket.save
  		flash[:success] = "You've purchased a ticket for #{event_time.event.title}!"
  		redirect_to dashboard_url
 		end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:dashboard]

  def dashboard
    @user = current_user
  end

  # Signs in as demo user
  def demo_sign_in
  user = User.find_by(email: 'demodan@example.com')
  sign_in(user)
  redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def datetime_formatter(datetime)
		datetime.strftime('%A %b %e @ %l:%M %p')
	end
	
end

app/helpers/event_times_helper.rb
module EventTimesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/event_times/_form.html.erb
<div class="row form-group">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for([event, event_time]) do |f| %>

      <%= render 'shared/error_messages', object: event_time %>

      <div class="form-group">
        <%= f.label :start_time %><br>
        <%= f.datetime_select :start_time, :ampm => true, :minute_step => 15 %>
      </div>

      <div class="form-group">
        <%= f.label :end_time %><br>
        <%= f.datetime_select :end_time, :ampm => true, :minute_step => 15 %>
      </div>

      <div class="form-group">
        <%= f.submit "Submit", class: "btn btn-primary btn-lg" %>
      </div>
    <% end %>
  </div>
</div>

app/views/event_times/edit.html.erb
<h1 class="center">Edit Date and Time for <%= @event.title %></h1>
<%= render 'form', event: @event, event_time: @event_time %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h3>Need to cancel?</h3>
    <p>No Stress. <%= button_to "Cancel this showtime", event_event_time_path(@event, @event_time), class: "btn btn-danger", data: { confirm: "This can not be undone." }, method: :delete %></p>
  </div>
</div>

app/views/event_times/new.html.erb
<h1 class="center">New Date and Time for <%= @event.title %></h1>
<%= render 'form', event: @event, event_time: @event_time %>

app/views/event_times/show.html.erb
<div class="col-sm-12">
  <h1><%= "#{@event.title}'s attendees" %></h1>
</div>
<div class="row">
  <div class="col-sm-10 col-sm-offset-1">
    <h4>
    <%= datetime_formatter(@event_time.start_time) %> to
    <%= datetime_formatter(@event_time.end_time) %>
  </h4>
  <br />
    <% if @event_time.tickets.empty? %>
      <h2>You currently have attendees.</h2>
      <p>When you have your first attendees, their name and email will show up here!</a></p>
    <% else %>
      <table class="table">
        <thead>
          <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
          </tr>
        </thead>
        <% @tickets.each do |ticket| %>
          <tbody>
            <td><%= ticket.attendee.first_name %></td>
            <td><%= ticket.attendee.last_name %></td>
            <td><%= ticket.attendee.email %></td>
          </tbody>
        <% end %>
      </table>
    <% end %>
  </div>
</div>

app/views/events/_event.html.erb
<li id="event-<%= event.id %>">
  <span class="title"><%= event.title %></span>
  <span class="description"><%= event.description %></span>
  <span class="location"><%= event.location %></span>
</li>

app/views/events/_event_times.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Start Time</th>
      <th>End Time</th>
      <% if current_user == event.manager %>
        <th>Attendees</th>
      <% end %>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% event_times.each do |event_time| %>
      <tr>
        <td><%= datetime_formatter(event_time.start_time) %></td>
        <td><%= datetime_formatter(event_time.end_time) %></td>
        <% if current_user == event.manager %>
          <td><%= link_to "#{event_time.tickets.count}", event_event_time_path(event, event_time), class: "btn btn-primary" %></td>
        <% end %>
        <% if current_user == event.manager && event_time.upcoming? %>
          <td><%= link_to "edit", edit_event_event_time_path(event, event_time), class: "btn btn-default" %></td>
        <% end %>
        <% if event_time.upcoming? %>
          <td>
            <%= form_for(ticket) do |f| %>
              <%= f.hidden_field :event_time_id, :value => event_time.id %>
              <%= f.submit 'buy ticket', class: 'btn btn-primary' %>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/events/_form.html.erb
<div class="row form-group">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(event) do |f| %>

      <%= render 'shared/error_messages', object: event %>

      <div class="form-group">
        <%= f.label :title %><br>
        <em>must be under 50 characters</em><br>
        <%= f.text_field :title, class:"form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :description %><br>
        <em>must be between 50 and 450 characters</em><br>
        <%= f.text_area :description, class:"form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :location %><br>
        <em>must be under 250 characters</em><br>
        <%= f.text_area :location, class:"form-control" %>
      </div>

      <div class="form-group">
        <%= f.submit "Submit", class: "btn btn-primary btn-lg" %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/edit.html.erb
<h1 class="center">Edit event</h1>
<%= render 'form', event: @event %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h3>Need to cancel?</h3>
    <p>No Stress. <%= button_to "Cancel my event", event_path(@event), class: "btn btn-danger", data: { confirm: "This can not be undone." }, method: :delete %></p>
  </div>
</div>

app/views/events/index.html.erb
<div class="col-md-6">
  <h1>Browse All Events</h1>
</div>
<div class="row">
  <div class="col-sm-10 col-sm-offset-1">
    <% if @events.empty? %>
      <h2>There are no events listed on Peanuts!.</h2>
      <p>Be the first to host an event! Get started <%= link_to "here", new_event_path %>.</p>
    <% else %>
      <table class="table">
        <thead>
          <tr>
            <th>Event</th>
            <th>Description</th>
            <th>Location</th>
            <th></th>
          </tr>
        </thead>
        <% @events.each do |event| %>
          <tbody>
            <td><%= event.title %></td>
            <td><%= event.description %></td>
            <td><%= event.location %></td>
            <td><%= link_to "more info", event_path(event), class: "btn btn-primary" %></td>
          </tbody>
        <% end %>
      </table>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<h1 class="center">New event</h1>
<%= render 'form', event: @event %>

app/views/events/show.html.erb
<div class="col-md-12">
  <h1><%= @event.title %></h1>
  <% if current_user == @event.manager %>
    <%= link_to "add tickets", new_event_event_time_path(@event), class: "btn btn-lg btn-primary" %>
  <% end %>
</div>
<div class="row">
  <div class="col-sm-10 col-sm-offset-1">
  <h4><%= @event.description %></h4>
  <br />
    <% if @event.event_times.empty? %>
      <h2>You currently have no show times.</h2>
      <p>Let's change that. To get started, <a href=<%= new_event_event_time_path(@event) %>>set up a show time or two.</a></p>
    <% else %>
      <% if !@event.event_times.upcoming.empty? %>
        <h2>Upcoming show times.</h2>
        <%= render 'event_times', event_times: @event.event_times.upcoming, 
                                  event:       @event, 
                                  ticket:      @ticket %>
      <% end %>
      <% if !@event.event_times.past.empty? %>
        <h2>Past show times.</h2>
        <%= render 'event_times', event_times: @event.event_times.past, 
                                  event:       @event,
                                  ticket:      @ticket %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-sm-4">
        <h1>about</h1>
          Peanuts empowers event managers, producers, and artists, (that's you!), with a super simple ticket sales platform.
      </div>
      <div class="col-sm-2 center">
        <%= link_to "create an account", new_user_registration_path %>
      </div>
      <div class="col-sm-2 center">
        <%= link_to "about", about_path %>
      </div>
      <div class="col-sm-2 center">
        <%= link_to "contributing", 'https://github.com/Thomascountz/peanuts', target: '_blank' %>
      </div>
      <div class="col-sm-2 center">
        <%= link_to 'thomas', 'http://thomascountz.github.io', target: '_blank' %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12">
        copy written with <3 by <a href="https://www.linkedin.com/in/morgan-thomas-5a7b9292/" title="Morgan Thomas">Morgan Thomas</a>
        </br>
        icons made by <a href="http://www.freepik.com" title="Freepik">Freepik</a> and by <a href="http://www.flaticon.com/authors/madebyoliver" title="Madebyoliver">Madebyoliver</a> from <a href="http://www.flaticon.com" title="Flaticon">www.flaticon.com</a> and is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <%= link_to "Peanuts", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "About",   about_path %></li>
        <% if user_signed_in? %>
        <li class="dropdown">
            <a href='#' class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Dashboard", dashboard_path %></li>
              <li><%= link_to "Account Settings", edit_user_registration_path %></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log in", new_user_session_path %></li>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Sign in as Demo Dan", demo_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <% flash.each do |type, msg| %>
      <% if type == "notice" %>
        <div class="alert alert-success">
      <% elsif type == "alert" %>
        <div class="alert alert-danger">
      <% else %>
        <div class='alert alert-<%= "#{type}" %>'>
      <% end %>
      <a href="#" class="close" data-dismiss="alert">&#215;</a>
      <ul>
        <li>
          <%= msg %>
        </li>
      </ul>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>peanuts</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/messages' %>
    <div id="content" class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explaination">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/_buttons.html.erb
<%= link_to "sell tickets", new_event_path, class: "btn btn-xlg btn-primary" %>
<%= link_to "buy tickets", events_path, class: "btn btn-xlg btn-primary" %>

app/views/static_pages/about.html.erb
<div>
  <div class="col-xs-8">
    <h1>Peanuts is a testament to the New York artist hustle.</h1>
    <h2>Who We Are</h2>
    <p>
      We are sculptors, composers, playwrights and thespians. Born from a group of artists, Peanuts is open source ticket sales platform. Artists make the content and we sell the tickets. It sounds so straightforward, right? 
    </p>
    <h2>What We Want</h2>
    <p>
      We want artists to receive the best visibility with no extra fees or stress. We want a platform for easy browsing and no hassle ticket purchases. We want artists to put on a performance and people to enjoy it. We are constantly working to streamline our users experience and stay true to our mission. It is no fuss on your part and that’s what we intended.
    </p>
  </div>
  <div class="col-xs-4">
    <%= image_tag("girl.png", alt: "girl", class: "img-responsive") %>
  </div>
</div>

app/views/static_pages/coming_soon.html.erb
<div>
  <div class="col-xs-8">
    <h1>Coming Soon!</h1>
    <h2>You're seeing this page because we haven't built this feature yet.</h2>
    <p>
      Peanuts is an ongoing passion project to create streamline services for artists. We want to pack in all of the features that we can, but we need some time to rehearse before the lights, camera, action! So check back here soon, because before you know it, we'll have finished adding all the bells and whistles.
    </p>
  </div>
  <div class="col-xs-4">
    <%= image_tag("man.png", alt: "man", class: "img-responsive") %>
  </div>
</div>

app/views/static_pages/index.html.erb
<div class="jumbotron">
  <div class="row">
    <div class="col-sm-6">
      <h1>peanuts.</h1>
      <h2>
        A minimal event tickets sales app.
      </h2>
      <div class="btn-group hidden-sm">
        <%= render 'buttons' %>
      </div>
      <div class="btn-group-vertical visible-sm">
        <%= render 'buttons' %>
      </div>
    </div>
    <div class="col-md-6">
      <%= image_tag('boy.png', alt: 'boy', class: 'img-responsive') %>
    </div>
  </div>
</div>

<div id="front-page" class="row">
  <div class="col-md-4">
    <%= image_tag('ticket.png', alt: 'ticket', class: 'img-responsive center-block') %>
    <p class="main-text">
      We all know New York has a lot to offer but no one tells us where to start. All you need to do is show up. We’ve got the rest covered.
    </p>
  </div>
  <div class="col-md-4">
    <%= image_tag('credit-card.png', alt: 'credit card', class: 'img-responsive center-block') %>
    <p class="main-text">
      You finally finished your mixed media performance piece? We’ll customize a virtual ticket. You can send it off to friends, family, neighbors, coworkers and first dates.
    </p>
  </div>
  <div class="col-md-4">
    <%= image_tag('puppet-show.png', alt: 'puppet show', class: 'img-responsive center-block') %>
    <p class="main-text">
      Our philosophy is simple--we want to support local artists, people like you (and us). Peanuts handles flawless tickets sales, so artists can do what they do best: create. 
    </p>
  </div>
</div>

app/views/users/_managed_events.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Location</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.description %></td>
        <td><%= event.location %></td>
        <td><%= link_to "view event", event_path(event), class: "btn btn-primary" %></td>
        <td><%= link_to "edit", edit_event_path(event), class: "btn btn-default" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_tickets.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Location</th>
      <th>Start Time</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.event_time.event.title %></td>
        <td><%= ticket.event_time.event.location %></td>
        <td><%= datetime_formatter(ticket.event_time.start_time) %></td>
        <td><%= link_to "view event", event_path(ticket.event_time.event), class: "btn btn-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/dashboard.html.erb
 <div class="col-sm-12">
  <h1>Hello <%= @user.first_name %>!</h1>
  <%= link_to "sell tickets", new_event_path, class: "btn btn-lg btn-primary" %>
  <%= link_to "buy tickets", events_path, class: "btn btn-lg btn-primary" %>
</div>
<br />
<div class="row">
  <div class="col-sm-10 col-sm-offset-1">
    <% if @user.managed_events.empty? && @user.tickets.empty?%>
      <h2>Welcome to your dashboard.</h2>
      <p>This is where the magic happens! See your events, track your sales, or just pull up your tickets and track your calendar. All in one place. We like to call this the peanut gallery, feel free to call it that too. To get started, <a href=<%= new_event_path %>>set up an event</a> or <a href=<%= coming_soon_path %>>purchase some tickets.</a></p>
    <% else %>
      <% if @user.managed_events.present? %>
        <h2>Events you manage.</h2>
        <%= render 'managed_events', events: @user.managed_events %>
      <% end %>
      <% if @user.tickets.present? %>
        <h2>Events you are attending.</h2>
        <%= render 'tickets', tickets: @user.tickets %>
      <% end %>
    <% end %>
  </div>
</div>